### PR TITLE
A bunch of updates to keep this tool relevant

### PR DESCRIPTION
**Pull request by piotrb**
- Added 4.2.2.0 to the version list with the few updated combinations
- Updated readme to not focus on 4.1 any more
- Added Gregtech to addon list since it adds 5 aspects

### CODE REVIEW

**Comment by Whitellama** [comment]
I might be doing something wrong... But when I checkout 6800564d7f423c92b10651c1f42f9ba07adad871 everything works normally, however when I checkout 3a53768e3efcc4a8e6f437a67082a06d775d36d9, I can't select the from and to dropdowns, making the tool unusable.

I can't figure out why that would be, because it's just a merge, and the changes appear exactly the same between the two commits... Anyone else experiencing this?

**Comment by piotrb** [comment]
Weird .. I had some local changes just sitting in my copy .. I swear this was all commited ..

**Comment by piotrb** [comment]
It should be working again

**Comment by ythri** [comment]
Ok, sorry for my long absence and thank you sooo much for all the updates and fixes. I finally got around to merging your changes (I only had to rename one last "stronito" to "stupidity" for GT and it seems to work fine now).

Thank you so much piotrb and also SpitefulFox and Whitellama!

**Pull request merged**
