### PR TITLE
Adding alphabetical order for aspects

### PR DESCRIPTION
**Pull request by chilled-kroete**

### CODE REVIEW

**Comment by Smashman** [comment]
The current sorting is actually the tier sorting that the game acknowledges.
It used to be alphabetical, but I changed it to this.

@ythri, what are your thoughts?

**Comment by ythri** [comment]
Actually, I think I prefer the alphabetical sorting, because if you have an aspect you want to connect, you always know its name, but usually not its tier.

I will probably merge this pull request tomorrow ... is that ok?

**Comment by Smashman** [comment]
It's your project! Though after thinking about it, I agree. :+1:

**Comment by ythri** [comment]
Ok, I merged it, thank you @x-mtd for the pull request.

One small note: I changed the compare function a tiny bit to return 0 for equal aspects (previously it would return 1). Not sure if this needed for sorting, but it felt strange without.

**Comment by Smashman** [comment]
Am I crazy, or does this completely not work?

**Comment by ythri** [comment]
Oh, now I see it. It does work, but only for the lists (From and To), not for the selection of available aspects. What I would find best: The order that you proposed in issue #23 for the selection of the available aspects, and pure alphabetical order for the lists From and To. What do you think?

Edit: Especially if we can ever fix issue #15, anything but alphabetical order would be awkward for the lists.

**Comment by Smashman** [comment]
Now in my pull request.

**Pull request merged**
