### PR TITLE
update for Thaumcraft 4.2.3.3

### PR DESCRIPTION
**Pull request by EXOgreen**
mind changed to fire/soul and weapon to tool/fire

### CODE REVIEW

**Comment by Whitellama** [comment]
I'm pretty sure those pluses aren't supposed to be there.

**Comment by EXOgreen** [comment]
Those pluses are added by Github automatically to indicate additions to the code. There are also minuses to shoe deletions of code that was previously there.

**Comment by ythri** [comment]
Thank you EXOgreen, I merged another pull request that changed the same aspects. The tool should be up to date now. I did not add both versions 4.2.2.0 and 4.2.3.3 since they both have the same aspect combinations.

Anyway, really appreciate your effort (and sorry for my long absence, I should have updated the tool a long time ago).

**Comment by EXOgreen** [comment]
Yes, I did notice the other pull request after making mine.  Another thing I did was create my own repository to try and update it a little more, specifically the mod aspects, because a few mods added or changed aspects, but never had the time.

**Pull request closed without merging**
