### PR TITLE
Multiple visual Changes: Combination Box in Result, Capitalization of Names, Darker hover-backgrounds, Type to Search

### PR DESCRIPTION
**Pull request by MaPePeR**
Changes:
- Show the combination-box also when hovering aspects in the search-result
- Capitalize all the Aspect Names 
- Darken the background color for hovered (brightest), unavailable and hovered+unavailable(darkest) Aspects 
- Type in the dropdown box to search for aspects (#15)

### CODE REVIEW

**Comment by Smashman** [comment]
Good start.

However, please fix both the sort within the select2 box and the vertical alignment of the images there too.

**Comment by MaPePeR** [comment]
I tried to fix the alignment. The sorting and searching should also work now properly.

**Comment by MaPePeR** [comment]
@Smashman anything else i should fix?

**Comment by ythri** [comment]
I tried it out and it seems to work fantastically (and looks better too - now that I see the difference, disabled aspects were really hard to discern before). I actually tried to implement type to search before, but wasn't able to with ddslick, and couldn't find another library that supported this, so your changes are really welcome. I will merge this for now, if I find any more bugs I will tell you (or just fix them myself, depending on how hard they are). Thanks again!

**Pull request merged**
