### PR TITLE
Updated Several Combinations to TC4.1g

### PR DESCRIPTION
**Pull request by KindarConrath**
Motion
Weather
Seed
Tree
Crop
Harvest

### CODE REVIEW

**Comment by Smashman** [comment]
This pull request would no longer merge correctly.

If you believe that some of the combinations are still out of date, please check the new way of formatting versions.

**Comment by KindarConrath** [comment]
I don't know if they are correct or not anymore as TC has moved on to 1.7 and I am not using that build yet.  I would however like to know what you mean for the future, what do you mean by "new way of formatting versions?"

**Comment by Smashman** [comment]
I recently did an overhaul of the site and added a version file that contains current and past combinations, which will allow those that do not want to update to still be able to use the site.

See [here](https://github.com/ythri/tcresearch/blob/gh-pages/version_dictionary.js).

If you could close the pull request, I would appreciate it.

**Comment by KindarConrath** [comment]
not a problem, and thank you :)

**Comment by KindarConrath** [comment]
Strange though, my fork was different, but showing that it wasn't behind... _ponder_

**Comment by Smashman** [comment]
I'm not 100% sure if the versions I have are correct, however.

Plus an extended history would be great. Do you perchance have some information on older versions?

**Comment by KindarConrath** [comment]
Not atm, though I could go back and test them.  I will double check 4.1g for sure as its the one that anyone on mc 1.6.4 should be using.

**Comment by KindarConrath** [comment]
Double checked your current version file for 4.1.0g, its all correct.

**Pull request closed without merging**
