### PR TITLE
Made numerous changes:

### LINKED ISSUE #18: Create version changer
I think this would be a great addition.

I will try creating this myself.

### PR DESCRIPTION
**Pull request by Smashman**
Version Dropdown - See version_dictionary.js to add more versions. (Closes https://github.com/ythri/tcresearch/issues/18)
Hovering over Aspects shows aspects required to created.
Results stay open - helpful to see more than one connection concurrently.
Aspects used count show at bottom of results.
Other stuff that I probably forgot, but was cool when I added it.

### CODE REVIEW

**Comment by Smashman** [comment]
Live version [here](http://smash.mn/tcresearch/) if you want to check everything works as before.

**Comment by ythri** [comment]
Wow, that's incredible (and right in time for the 1.7 version of thaumcraft). I will have a look when I'm back at home.

**Comment by Smashman** [comment]
Yeah, that's what prompted me to make the changes. I noticed that a few aspects had been removed.

Let me know what you think, when you can!

**Comment by Smashman** [comment]
I've put a few more things in, including the new update.

Do you happen to know when you'll be able to look it over? Thanks.

**Comment by ythri** [comment]
Ok, I didn't have time by now, too many deadlines all at once. I will merge your request for now, so anyone can benefit from it, and have a better look during the weekend (yeah, no work during easter). The glimpses I got on your changes look fantastic, a total cleanup of all the clutter. Never got around to do it so far. I will also add the new Thaumcraft 4.1.1.9 aspects to the version changer during the weekend if you didn't do that already. _Edit: You did, of course :)_

Anyway, thanks again for all your work.

**Comment by Smashman** [comment]
I did add the 4.1.1.9 combinations.

Thanks for merging! :+1:

**Pull request merged**
